#!/usr/bin/env python3
"""Which translation unit does an address belong to?

Scans orig/LEGOBatman.exe for `push <addr of leaked __FILE__ string>` inside
known functions (from ghidra/LEGOBatman.exe.stats.tsv). Functions are laid out
in link order, so the anchors bound address ranges per source file. Prints a
markdown table; `make linkmap` writes docs/linkmap.md.

Usage: tools/linkmap.py [ADDR ...]   (with addresses: print the bracketing anchors)
"""
import bisect, re, struct, sys
import pefile

EXE = "orig/LEGOBatman.exe"
STATS = "ghidra/LEGOBatman.exe.stats.tsv"

def main(argv):
    pe = pefile.PE(EXE); base = pe.OPTIONAL_HEADER.ImageBase
    sec = {s.Name.rstrip(b"\0").decode(): s for s in pe.sections}
    rdata, rbase = sec[".rdata"].get_data(), base + sec[".rdata"].VirtualAddress
    text, tbase = sec[".text"].get_data(), base + sec[".text"].VirtualAddress
    strs = {}
    for m in re.finditer(rb"[a-zA-Z]:\\[^\x00]{8,200}?\.(?:cpp|c|h)\x00|\.\\[^\x00]{3,60}?\.cpp\x00", rdata):
        strs[rbase + m.start()] = m.group().rstrip(b"\0").decode(errors="replace")
    funcs = sorted((int(a, 16), int(s)) for a, s, _, _ in
                   (l.rstrip("\n").split("\t") for l in open(STATS) if not l.startswith("#")))
    starts = [a for a, _ in funcs]
    def containing(va):
        i = bisect.bisect_right(starts, va) - 1
        return funcs[i][0] if i >= 0 and va < funcs[i][0] + funcs[i][1] else None
    hits = {}
    for off in range(len(text) - 5):
        if text[off] == 0x68:  # push imm32
            imm = struct.unpack_from("<I", text, off + 1)[0]
            if imm in strs:
                f = containing(tbase + off)
                if f:
                    hits.setdefault(f, set()).add(strs[imm])
    rows = sorted((f, sorted(v)) for f, v in hits.items())
    if argv:
        for a in argv:
            va = int(a, 16)
            prev = max((r for r in rows if r[0] <= va), default=None)
            nxt = min((r for r in rows if r[0] > va), default=None)
            fmt = lambda r: f"{r[0]:08x} {', '.join(p.split(chr(92))[-1] for p in r[1])}" if r else "-"
            print(f"{va:08x}: after [{fmt(prev)}]  before [{fmt(nxt)}]")
        return
    print("# link map\n")
    print("Functions that reference a leaked `__FILE__` string, in address order.")
    print("Everything between two anchors was linked from objects between those")
    print("files. Generated by `tools/linkmap.py`; do not edit.\n")
    print("| anchor function | source file(s) |")
    print("|---|---|")
    for f, v in rows:
        print(f"| `{f:08x}` | " + ", ".join("`" + p.replace("c:\\tt\\legobatman1_clean\\batman_resub2\\", "").replace("\\", "/") + "`" for p in v) + " |")

if __name__ == "__main__":
    main(sys.argv[1:])
