#!/usr/bin/env python3
"""Progress: badge, map and todo list, all derived from src/ annotations.

    tools/progress.py            print the summary
    tools/progress.py --write    also rewrite README badge, docs/todo.md,
                                 site/data.json (the pre-commit hook runs this)

Inputs (all tracked, so this works on a fresh clone):
  tools/symbols/functions.tsv   every function ghidra found in game code
  tools/symbols/pc-names.csv    PC <-> Mac 1.0.1 names
  docs/linkmap.md               leaked source-file anchors
  src/**                        // FUNCTION: / // STUB: annotations
  ref/saga/src (optional)       marks todo items that already have a saga body

Library functions (FID/EH-named by ghidra) are excluded from the denominator.
"""
import csv, re, sys
from collections import defaultdict
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
TEXT_LO, TEXT_HI = 0x00401000, 0x0073C8FB  # game region of .text (docs/recon.md)
ANNOT = re.compile(r"//\s*(FUNCTION|STUB):\s*LEGOBATMAN\s+0x([0-9a-fA-F]+)")

MATCHED, STUB, NAMED, UNKNOWN = "matched", "stub", "named", "unknown"
METHOD = {}                   # addr -> how its name was paired (tools/macnames.py)
WEAK = ("order", "gapfill")


def load():
    funcs = {}  # addr -> (size, ghidra name)
    for line in open(ROOT / "tools/symbols/functions.tsv"):
        if line.startswith("#"):
            continue
        a, s, n = line.rstrip("\n").split("\t")
        funcs[int(a, 16)] = (int(s), n)
    lib = {a for a, (_, n) in funcs.items() if not n.startswith(("FUN_", "thunk_"))}

    names = {}
    for r in csv.DictReader(open(ROOT / "tools/symbols/pc-names.csv")):
        names[int(r["pc_addr"], 16)] = r["demangled"]
        METHOD[int(r["pc_addr"], 16)] = r["method"]
    state = {}
    for f in list(ROOT.glob("src/**/*.c")) + list(ROOT.glob("src/**/*.cpp")) + list(ROOT.glob("src/**/*.h")):
        for kind, a in ANNOT.findall(f.read_text(errors="ignore")):
            a = int(a, 16)
            if state.get(a) != MATCHED:
                state[a] = MATCHED if kind == "FUNCTION" else STUB
    for a in funcs:
        if a not in state:
            state[a] = NAMED if a in names else UNKNOWN
    return funcs, lib, names, state


def saga_bodies():
    root = ROOT / "ref/saga/src"
    defs = {}
    if not root.is_dir():
        return defs
    pat = re.compile(r"^[A-Za-z_][\w\s\*&:<>,]*?\b((?:\w+::)?~?\w+)\s*\([^;{]*\)\s*(?:const\s*)?\{", re.M)
    for f in list(root.rglob("*.c")) + list(root.rglob("*.cpp")):
        for m in pat.finditer(f.read_text(errors="ignore")):
            defs.setdefault(m.group(1), f.relative_to(root).as_posix())
    if not defs:
        sys.exit("progress: ref/saga/src exists but no saga definitions were found; "
                 "check the submodule (git submodule update --init) before regenerating")
    return defs


def anchors():
    out = []
    p = ROOT / "docs/linkmap.md"
    if p.exists():
        for m in re.finditer(r"^\| `([0-9a-f]{8})` \| `([^`]+)`", p.read_text(), re.M):
            out.append((int(m.group(1), 16), m.group(2).split("/")[-1]))
    return sorted(out)


def summary(funcs, lib, state):
    game = {a: s for a, (s, _) in funcs.items() if a not in lib}
    total = sum(game.values())
    by = defaultdict(lambda: [0, 0])
    for a, s in game.items():
        by[state[a]][0] += 1
        by[state[a]][1] += s
    pct = 100.0 * by[MATCHED][1] / total if total else 0.0
    return total, by, pct


# --- README badge -------------------------------------------------------------
def write_badge(pct):
    color = ("brightgreen" if pct >= 90 else "green" if pct >= 70 else
             "yellow" if pct >= 50 else "orange" if pct >= 30 else "red")
    badge = f"https://img.shields.io/badge/match%20progress-{pct:.2f}%25-{color}"
    readme = ROOT / "README.md"
    t = re.sub(r"https://img\.shields\.io/badge/match%20progress-[^)]*", badge, readme.read_text())
    readme.write_text(t)


# --- docs/todo.md: named functions not done yet --------------------------------
def group_of(name):
    base = name.split("(")[0].strip()
    base = base.split(" ")[-1] if " " in base and "operator" not in base else base
    if "::" in base:
        return base.split("::")[0]
    base = base.lstrip("_")
    if "_" in base:
        return base.split("_")[0]
    m = re.match(r"(Nu[A-Z][a-z0-9]+)", base)
    return m.group(1) if m else None


def write_todo(funcs, state, names, saga, by):
    groups = defaultdict(list)
    anc = anchors()
    for a, (s, _) in funcs.items():
        if state[a] in (NAMED, STUB) and a in names:
            n = names[a]
            short = n.split("(")[0].lstrip("_")
            g = group_of(n)
            if g is None:
                prev = [f for x, f in anc if x <= a]
                g = f"near {prev[-1]}" if prev else "start of .text"
            groups[g].append((s, a, n, state[a], saga.get(short)))
    lines = [
        "# todo",
        "",
        "Generated by `tools/progress.py` on every commit (pre-commit hook); do not",
        "edit. A function disappears from here once a `// FUNCTION:` annotation for",
        "it lands in `src/`. Only functions whose real name is known (paired from",
        "the Mac build) are listed; the other "
        f"{by[UNKNOWN][0]:,} are in `tools/symbols/functions.tsv`.",
        "",
        "Smallest first inside each group. **saga** = opensagadev/saga has a body",
        "for it under `ref/saga/src/` (a starting point, not a guaranteed match).",
        "**stub** = written but not byte-identical yet. **hint** = the name comes",
        "from a weak Mac pairing (order/gapfill): check the code agrees; fix it in",
        "`tools/symbols/confirmed.txt` or `rejected.txt`.",
        "",
    ]
    order = sorted(groups.items(), key=lambda kv: (-sum(1 for x in kv[1] if x[4]), kv[0].lower()))
    lines.append("| group | todo | with saga body |")
    lines.append("|---|---|---|")
    for g, items in order:
        slug = re.sub(r"[^a-z0-9 _-]", "", g.lower()).replace(" ", "-")
        lines.append(f"| [{g}](#{slug}) | {len(items)} | {sum(1 for x in items if x[4])} |")
    lines.append("")
    for g, items in order:
        lines.append(f"## {g}")
        lines.append("")
        for s, a, n, st, sg in sorted(items):
            tags = []
            if st == STUB:
                tags.append("**stub**")
            if METHOD.get(a) in WEAK:
                tags.append(f"**hint** name ({METHOD[a]})")
            if sg:
                tags.append(f"**saga** `{sg}`")
            lines.append(f"- [ ] `{a:08x}` {s} B `{n}`" + ("  " + " · ".join(tags) if tags else ""))
        lines.append("")
    (ROOT / "docs/todo.md").write_text("\n".join(lines))


# --- site/data.json: everything the GitHub Pages map needs --------------------
def write_site(funcs, lib, names, state, saga, total, by, pct):
    import json, datetime
    where, src_name = {}, {}
    decl = re.compile(r"//\s*(?:FUNCTION|STUB):\s*LEGOBATMAN\s+0x([0-9a-fA-F]+)\n(?:\s*//.*\n)*\s*([^\n{;]*?)\s*(?:\{|;|$)", re.M)
    for f in list(ROOT.glob("src/**/*.c")) + list(ROOT.glob("src/**/*.cpp")) + list(ROOT.glob("src/**/*.h")):
        text = f.read_text(errors="ignore")
        for m in decl.finditer(text):
            a = int(m.group(1), 16)
            where.setdefault(a, f.relative_to(ROOT).as_posix())
            src_name.setdefault(a, m.group(2).strip())
    code = {MATCHED: "m", STUB: "s", NAMED: "n", UNKNOWN: "u"}
    rows = []
    for a in sorted(funcs):
        s, gname = funcs[a]
        st = code[state[a]] if state[a] in (MATCHED, STUB) else "l" if a in lib else code[state[a]]
        name = src_name.get(a) or names.get(a) or (None if gname.startswith(("FUN_", "thunk_")) else gname)
        short = (name or "").split("(")[0].split(" ")[-1].lstrip("_")
        rows.append([a, s, st, name, where.get(a), saga.get(short) if name else None,
                     None if a in src_name else METHOD.get(a)])
    data = {
        "generated": datetime.date.today().isoformat(),
        "text": [TEXT_LO, TEXT_HI], "total": total, "pct": round(pct, 3),
        "counts": {k: by[k][0] for k in (MATCHED, STUB, NAMED, UNKNOWN)},
        "bytes": {k: by[k][1] for k in (MATCHED, STUB, NAMED, UNKNOWN)},
        "anchors": anchors(),
        "functions": rows,
    }
    (ROOT / "site").mkdir(exist_ok=True)
    (ROOT / "site/data.json").write_text(json.dumps(data, separators=(",", ":")))


def main(argv):
    funcs, lib, names, state = load()
    total, by, pct = summary(funcs, lib, state)
    print(f"{by[MATCHED][0]} functions matched, {by[MATCHED][1]:,} / {total:,} bytes of game code "
          f"({pct:.2f}%); {by[STUB][0]} stubs; {by[NAMED][0]} named todo; {by[UNKNOWN][0]} unnamed todo.")
    if "--write" in argv or "--readme" in argv:
        write_badge(pct)
        saga = saga_bodies()
        write_todo(funcs, state, names, saga, by)
        write_site(funcs, lib, names, state, saga, total, by, pct)


if __name__ == "__main__":
    main(sys.argv[1:])
